#!/usr/bin/env bash
set -euo pipefail

# -----------------------------
# omarchy-gaming install script
# -----------------------------
# Targets: Arch-based (Omarchy), Pure Wayland/Hyprland, NVIDIA RTX 30xx
# Safe to re-run (idempotent-ish). Creates backups before changes.

log()  { printf "\n\033[1;32m[omarchy-gaming]\033[0m %s\n" "$*"; }
warn() { printf "\n\033[1;33m[warn]\033[0m %s\n" "$*"; }
die()  { printf "\n\033[1;31m[error]\033[0m %s\n" "$*"; exit 1; }

need_cmd() { command -v "$1" >/dev/null 2>&1; }

if [[ ${EUID:-999} -eq 0 ]]; then
  die "Do not run as root. Run as your user; the script will sudo as needed."
fi

if ! need_cmd pacman; then
  die "pacman not found. This script targets Arch/Arch-based systems (Omarchy)."
fi

# -----------------------------
# User-configurable toggles
# -----------------------------
INSTALL_LTS_KERNEL="${INSTALL_LTS_KERNEL:-0}"   # 1 = install linux-lts + headers
ENABLE_HYPR_VRR="${ENABLE_HYPR_VRR:-1}"         # 0 = skip VRR snippet
SET_NVIDIA_ENV="${SET_NVIDIA_ENV:-1}"           # 0 = skip NVIDIA env vars snippet
APPLY_MODESET_PARAM="${APPLY_MODESET_PARAM:-1}" # 0 = don't touch bootloader cmdline

# -----------------------------
# Backup Hyprland config
# -----------------------------
backup_hypr() {
  local cfg_dir="${XDG_CONFIG_HOME:-$HOME/.config}/hypr"
  if [[ ! -d "$cfg_dir" ]]; then
    warn "Hyprland config not found at $cfg_dir — skipping Hypr backup."
    return 0
  fi

  local backup_dir="$HOME/omarchy-backups"
  mkdir -p "$backup_dir"
  local out="$backup_dir/hypr-$(date +%Y%m%d-%H%M%S).tar.gz"
  tar -czf "$out" -C "${XDG_CONFIG_HOME:-$HOME/.config}" hypr
  log "Backed up Hyprland config to: $out"
}
backup_hypr

# -----------------------------
# Packages
# -----------------------------
BASE_PKGS=(
  steam
  gamescope
  mangohud
  lib32-mangohud
  gamemode
  vulkan-tools
  vulkan-icd-loader
  lib32-vulkan-icd-loader
  pipewire pipewire-alsa pipewire-pulse wireplumber
  steam-devices
)

# NVIDIA stack (DKMS for kernel flexibility)
NVIDIA_PKGS=(
  nvidia-dkms
  nvidia-utils
  lib32-nvidia-utils
)

LTS_PKGS=(linux-lts linux-lts-headers)

AUR_PKGS=(protonup-qt)

# -----------------------------
# Install packages
# -----------------------------
log "Updating system + installing core gaming packages..."
sudo pacman -Syu --needed --noconfirm "${BASE_PKGS[@]}"

log "Installing NVIDIA driver stack (DKMS)..."
sudo pacman -S --needed --noconfirm "${NVIDIA_PKGS[@]}"

if [[ "$INSTALL_LTS_KERNEL" == "1" ]]; then
  log "Installing LTS kernel..."
  sudo pacman -S --needed --noconfirm "${LTS_PKGS[@]}"
else
  warn "Skipping linux-lts. (Set INSTALL_LTS_KERNEL=1 to install it.)"
fi

# -----------------------------
# Enable services
# -----------------------------
log "Enabling WirePlumber (user audio session manager)..."
systemctl --user enable --now wireplumber.service >/dev/null 2>&1 || true

log "Enabling GameMode daemon (user)..."
systemctl --user enable --now gamemoded.service >/dev/null 2>&1 || true

# -----------------------------
# Hyprland drop-in config
# -----------------------------
write_hypr_dropin() {
  local hypr_dir="${XDG_CONFIG_HOME:-$HOME/.config}/hypr"
  mkdir -p "$hypr_dir/conf.d"

  local conf_file="$hypr_dir/conf.d/99-gaming.conf"

  log "Writing Hyprland gaming drop-in: $conf_file"
  {
    echo "# Generated by omarchy-gaming install.sh"
    echo "# Safe to edit. Re-running install.sh will overwrite this file."
    echo

    if [[ "$SET_NVIDIA_ENV" == "1" ]]; then
      echo "# NVIDIA + Wayland (GBM) – Hyprland-recommended env vars"
      echo "env = GBM_BACKEND,nvidia-drm"
      echo "env = __GLX_VENDOR_LIBRARY_NAME,nvidia"
      echo "env = LIBVA_DRIVER_NAME,nvidia"
      echo
      echo "# If you see cursor corruption, uncomment:"
      echo "# env = WLR_NO_HARDWARE_CURSORS,1"
      echo
      echo "# If Firefox is unstable on NVIDIA, Hyprland suggests removing GBM_BACKEND."
      echo "# (Keep __GLX_VENDOR_LIBRARY_NAME.)"
      echo
    else
      echo "# NVIDIA env vars skipped (SET_NVIDIA_ENV=0)"
      echo
    fi

    if [[ "$ENABLE_HYPR_VRR" == "1" ]]; then
      echo "# VRR (Adaptive Sync)"
      echo "# vrr = 1 enables VRR always; some displays may flicker."
      echo "misc {"
      echo "  vrr = 1"
      echo "}"
      echo
    else
      echo "# VRR skipped (ENABLE_HYPR_VRR=0)"
      echo
    fi

    echo "# Notes:"
    echo "# - Prefer running games with gamescope (Steam launch options)."
    echo "# - Example: gamescope -f -r 144 --adaptive-sync -- %command%"
  } | tee "$conf_file" >/dev/null
}
write_hypr_dropin

# -----------------------------
# Bootloader: ensure nvidia-drm.modeset=1
# -----------------------------
ensure_nvidia_modeset() {
  local param="nvidia-drm.modeset=1"

  if [[ "$APPLY_MODESET_PARAM" != "1" ]]; then
    warn "Skipping bootloader cmdline update (APPLY_MODESET_PARAM=0)."
    warn "You should still ensure kernel cmdline includes: $param"
    return 0
  fi

  log "Ensuring kernel cmdline contains: $param"

  # systemd-boot entries
  if [[ -d /boot/loader/entries ]]; then
    log "Detected systemd-boot entries in /boot/loader/entries"
    local changed=0

    for f in /boot/loader/entries/*.conf; do
      [[ -f "$f" ]] || continue

      if grep -q "$param" "$f"; then
        continue
      fi

      if grep -qE '^\s*options\s+' "$f"; then
        # Insert param at start of options line
        sudo sed -i "s/^\(\s*options\s\+\)/\1$param /" "$f"
        changed=1
        log "Updated: $f"
      else
        # If no options line exists (rare), append
        echo "options $param" | sudo tee -a "$f" >/dev/null
        changed=1
        log "Appended options to: $f"
      fi
    done

    if [[ "$changed" -eq 1 ]]; then
      log "systemd-boot entries updated."
    else
      log "systemd-boot already configured."
    fi
    return 0
  fi

  # GRUB
  if [[ -f /etc/default/grub ]]; then
    log "Detected GRUB config at /etc/default/grub"

    if grep -q "$param" /etc/default/grub; then
      log "GRUB already contains $param"
      return 0
    fi

    if grep -q 'GRUB_CMDLINE_LINUX_DEFAULT=' /etc/default/grub; then
      sudo sed -i "s/^\(GRUB_CMDLINE_LINUX_DEFAULT=\"[^\"]*\)\"/\1 $param\"/" /etc/default/grub
      log "Added $param to GRUB_CMDLINE_LINUX_DEFAULT"
    else
      warn "GRUB_CMDLINE_LINUX_DEFAULT not found in /etc/default/grub. Add $param manually."
      return 0
    fi

    if command -v grub-mkconfig >/dev/null 2>&1; then
      if [[ -d /boot/grub ]]; then
        sudo grub-mkconfig -o /boot/grub/grub.cfg
        log "Regenerated GRUB config: /boot/grub/grub.cfg"
      elif [[ -d /boot/grub2 ]]; then
        sudo grub-mkconfig -o /boot/grub2/grub.cfg
        log "Regenerated GRUB config: /boot/grub2/grub.cfg"
      else
        warn "Could not find /boot/grub or /boot/grub2. Regenerate GRUB manually."
      fi
    else
      warn "grub-mkconfig not found. Regenerate GRUB config manually."
    fi

    return 0
  fi

  warn "Could not detect systemd-boot or GRUB."
  warn "Add '$param' manually to your bootloader kernel parameters."
}
ensure_nvidia_modeset

# -----------------------------
# AUR helper / ProtonUp-Qt
# -----------------------------
if need_cmd yay; then
  log "Installing AUR packages with yay: ${AUR_PKGS[*]}"
  yay -S --needed --noconfirm "${AUR_PKGS[@]}"
else
  warn "yay not found. Install yay, then run:"
  warn "  yay -S --needed protonup-qt"
fi

# -----------------------------
# Final notes + verification
# -----------------------------
warn "REBOOT recommended to load NVIDIA DRM modeset + new kernel modules."
warn "After reboot, verify modeset is enabled:"
warn "  cat /sys/module/nvidia_drm/parameters/modeset   # expect: Y"
warn
warn "Steam launch option example (1440p/144Hz):"
warn "  gamescope -W 2560 -H 1440 -r 144 -- %command%"
warn "Or fullscreen + VRR:"
warn "  gamescope -f -r 144 --adaptive-sync -- %command%"
warn
log "All done."
